services:
  teams-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teams-mcp-server
    ports:
      - "${TEAMS_MCP_PORT:-8003}:8003"
    environment:
      # Microsoft OAuth Configuration
      - MICROSOFT_OAUTH_CLIENT_ID=${MICROSOFT_OAUTH_CLIENT_ID}
      - MICROSOFT_OAUTH_CLIENT_SECRET=${MICROSOFT_OAUTH_CLIENT_SECRET}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID:-common}
      
      # Server Configuration
      - TEAMS_MCP_BASE_URI=${TEAMS_MCP_BASE_URI:-http://localhost}
      - MICROSOFT_OAUTH_REDIRECT_URI=${MICROSOFT_OAUTH_REDIRECT_URI:-http://localhost:8003/callback}
      
      # OAuth 2.1 Settings
      - MCP_ENABLE_OAUTH21=true
      - OAUTH2_ALLOW_INSECURE_TRANSPORT=${OAUTH2_ALLOW_INSECURE_TRANSPORT:-false}
      
      # Development Settings
      - SKIP_AUTH=${SKIP_AUTH:-false}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    
    volumes:
      # Persist credentials
      - teams_mcp_credentials:/app/.microsoft_teams_mcp/credentials
      
    restart: unless-stopped
    
    networks:
      - default

volumes:
  teams_mcp_credentials:
    driver: local


